name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          VITE_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
